// passages.ts

interface PassageData {
    [key: string]: string;
}

export const passageData: PassageData = {
    '18': `To whom it may concern,
I am writing on behalf of the students’ council. We are planning to hold a music festival on the last day of the semester. To make the festival more special, we want to invite a famous band to perform. We believe that your band, “The Starlights,” would be a perfect fit for our event. The students love your music, and your performance would make the festival an unforgettable experience for everyone. We would be honored if you could join us. We look forward to hearing from you soon.
Sincerely,
The Students’ Council`,
    '19': `The moment the new roller coaster started its climb, my excitement quickly turned to fear. The slow ascent felt like it was lasting forever, building up the tension inside me. When we reached the peak and I saw the steep drop below, my heart pounded in my chest. I held on tight as we plunged down at an incredible speed. The wind rushed past my face, and I couldn't help but scream. But as the ride continued with its twists and turns, my fear began to transform into exhilaration. By the time the roller coaster came to a stop, I was breathless but laughing, ready to go on it again.`,
    '20': `We often hear that it's important to accept our imperfections, but this is easier said than done. We live in a society that constantly shows us images of perfection, making it hard not to compare ourselves. However, striving for perfection can be harmful. It can lead to anxiety, stress, and a constant feeling of not being good enough. Instead of chasing an unrealistic ideal, we should learn to embrace our flaws. Our imperfections are part of what makes us unique individuals. True self-acceptance comes from understanding that being imperfect is completely normal and human.`,
    '21': `In the digital age, data is the new oil. Companies collect vast amounts of information about our online behavior, preferences, and even our location. This data is incredibly valuable, as it allows for targeted advertising and personalized services. However, this raises serious privacy concerns. Who owns this data, and how is it being used? Many people are unaware of how much of their personal information is being shared and sold. There is a growing need for greater transparency and control for users over their own data. Without proper regulations, we risk creating a world where our personal lives are open books for corporations to read.`,
    '22': `When a predator is near, some animals release a chemical signal to warn others of the danger. For example, when a minnow is caught by a pike, its skin releases a substance that alerts other minnows in the area. This "alarm substance" causes them to flee and hide. This behavior is not learned; it's an innate response. Interestingly, this chemical signal is not species-specific. Other fish species can also detect the minnow's alarm substance and will react as if their own species were in danger. This shared warning system benefits the entire aquatic community, increasing the chances of survival for many different fish.`,
    '23': `The concept of "home" is different for everyone. For some, it is a physical place, the house where they grew up, filled with childhood memories. For others, home is not tied to a specific building but to the people they love. It's the feeling of comfort and belonging they get when they are with their family or close friends. There are also those for whom home is a state of mind, a sense of inner peace and identity that they carry with them wherever they go. Ultimately, home is where we feel safe, accepted, and truly ourselves, regardless of its physical form or location.`,
    '24': `The graph above shows the percentage of people in different age groups who reported using social media to get news in 2020 and 2022. ① In both years, the 18-29 age group had the highest percentage of social media news users. ② The percentage of users decreased as the age of the group increased in both years. ③ The 30-49 age group showed a slight increase in usage from 2020 to 2022. ④ The 50-64 age group was the only group where the percentage of users remained exactly the same across the two years. ⑤ The 65 and older group consistently had the lowest percentage of social media news users in both years.`,
    '26': `Charles Henry Turner was a pioneering African American biologist and zoologist. Born in 1867, he showed a keen interest in insects and animal behavior from a young age. Despite facing significant racial barriers, Turner earned a Ph.D. in zoology from the University of Chicago, becoming one of the first African Americans to do so. His research demonstrated that insects are capable of learning and can modify their behavior based on experience. For instance, he proved that bees can see in color and recognize patterns. Although he was never offered a major university position worthy of his qualifications, he taught high school and continued his groundbreaking research until his death in 1923.`,
    '29': `While we may think our choices are driven by our personal preferences, we are often influenced by social norms without even realizing it. Social norms are the unwritten rules of behavior shared by members of a given group or society. They tell us what is considered acceptable or unacceptable. For example, we might stand in line to wait for a bus not because there is a physical barrier stopping us, but because it is the social norm. Deviating from these norms can lead to social disapproval or even exclusion. This powerful force of social pressure guides much of our daily behavior, ensuring that society functions in a relatively orderly and predictable way.`,
    '30': `The advertisement showed a smiling family enjoying a new brand of cereal. The sun was shining, the kids were laughing, and everything seemed perfect. The hidden message was clear: buying this cereal will make your family as happy as the one in the picture. This technique, known as "emotional association," is a powerful tool in advertising. It works by linking a product with a positive feeling or a desirable outcome. The goal is not to sell the product based on its features or quality but on the emotions it evokes. Consumers are often unaware of this manipulation, making choices based on feelings rather than rational thought.`,
    '31': `One of the most effective ways to improve your memory is through a technique called "spaced repetition." This involves reviewing information at increasing intervals over time. For example, instead of cramming for a test the night before, you would study the material on day one, then again on day three, then on day seven, and so on. The reason this works is that each time you recall a piece of information, the neural pathway to that memory becomes stronger. By spacing out the reviews, you are telling your brain that this information is important and needs to be retained for the long term. This method is far more efficient for creating lasting memories than massed practice.`,
    '32': `Creativity is not something that is limited to artists and musicians. It is a fundamental human skill that can be applied in any field, from science to business. At its core, creativity is about problem-solving. It's the ability to see things from a different perspective and to connect seemingly unrelated ideas to form a new and useful solution. To foster creativity, it is essential to be open to new experiences, to question assumptions, and not to be afraid of making mistakes. Mistakes are not failures; they are learning opportunities that can lead to unexpected breakthroughs. Every individual has the potential to be creative if they cultivate the right mindset.`,
    '33': `In a classic experiment, a group of people were asked to watch a video of two teams passing basketballs and count the number of passes made by one team. During the video, a person in a gorilla costume walked through the scene, stopped in the middle, and thumped their chest. Surprisingly, about half of the participants did not notice the gorilla at all. This phenomenon is known as "inattentional blindness." It demonstrates that we are often blind to things in our visual field if we are not paying attention to them. Our attention is a limited resource, and when we focus intensely on one task, we can miss even the most obvious and unexpected events happening right in front of us.`,
    '34': `When we interact with others, we tend to subtly mimic their posture, gestures, and facial expressions. This is known as the "chameleon effect," and it happens largely unconsciously. This mimicry serves an important social function: it facilitates liking and creates a smoother interaction. When you mimic someone, they are more likely to perceive you as empathetic and agreeable. This can help in building rapport and trust. The effect works both ways; we are also more likely to have positive feelings towards someone who mimics us. This automatic imitation is a fundamental part of social intelligence, helping us to connect and empathize with those around us.`,
    '35': `The introduction of a new species into an ecosystem can have devastating consequences. These "invasive species" often have no natural predators in their new environment, allowing their populations to grow unchecked. A classic example is the cane toad in Australia. It was introduced to control pests in sugarcane fields, but it quickly became a much bigger problem. The toads are toxic, killing native predators that try to eat them. They also compete with native species for food and resources. The cane toad's story is a powerful reminder of the complex web of interactions within an ecosystem and the dangers of interfering with it without fully understanding the potential outcomes.`,
    '36': `Ancient Greek philosophers were among the first to systematically explore the natural world using reason rather than mythology. They observed phenomena, from the movement of the stars to the properties of matter, and sought to find logical explanations. Thales, for example, proposed that all things were ultimately made of water. While incorrect, this was a revolutionary step because it attempted to explain the universe based on a single, natural substance. This shift from supernatural to natural explanations laid the foundation for Western science and philosophy. It was the beginning of a tradition of critical inquiry and rational thought that continues to shape our understanding of the world today.`,
    '37': `Consider a situation where you are offered two jobs. Job A offers a higher salary but is very stressful and has long hours. Job B has a lower salary but offers a better work-life balance and more enjoyable work. The choice is not easy. This is an example of an approach-approach conflict, where you must choose between two desirable options. However, your decision-making process can be influenced by how the options are framed. If the choice is framed in terms of gains (e.g., "choose the higher salary"), people might lean towards Job A. If it's framed in terms of losses (e.g., "avoid the stressful environment"), they might prefer Job B. This shows that our choices are not always purely rational but can be swayed by the presentation of the options.`,
    '38': `Human beings have an innate need to belong. We are social creatures who thrive on connection and community. From an evolutionary perspective, this makes sense. Our ancestors' survival depended on being part of a group, which provided protection, shared resources, and opportunities for reproduction. This fundamental drive to form and maintain relationships continues to be a powerful motivator of human behavior today. Feeling a sense of belonging is crucial for our psychological well-being. It is associated with higher levels of happiness, self-esteem, and physical health, while social exclusion and loneliness can have serious negative effects.`,
    '39': `When you look at a painting, you don't just see a collection of colors and shapes. Your brain actively interprets the visual information based on your past experiences, expectations, and knowledge of the world. For example, if you see a small figure next to a large building, you perceive the figure as being farther away, not as being a tiny person. This is due to a principle called "perceptual constancy," where we perceive objects as being stable and unchanging despite changes in the sensory information we receive. Our perception is not a passive reception of reality but an active construction, a best guess about what is out there in the world.`,
    '40': `To summarize, the key to effective communication is not just about what you say, but how you say it. Nonverbal cues, such as body language, tone of voice, and eye contact, play a massive role in conveying your message. An open posture can signal confidence, while a hesitant tone might suggest uncertainty, regardless of the words used. It is also crucial to be an active listener, paying full attention to the other person and showing that you understand their perspective. By mastering both verbal and nonverbal skills, and by practicing empathetic listening, you can build stronger relationships and avoid misunderstandings.`,
    '41-42': `In our quest for success, we often focus on acquiring more knowledge and skills. We believe that adding to our repertoire is the path to improvement. However, sometimes the most significant progress comes not from addition, but from subtraction. Think of a sculptor who creates a masterpiece by chipping away at a block of stone. The art is already there; the sculptor's job is to remove what is unnecessary.
Similarly, in our own lives and work, we can often achieve more by eliminating distractions, bad habits, and mental clutter. Removing a non-essential task can free up more time and energy than learning a new productivity hack. Unlearning a limiting belief can be more powerful than gaining a new piece of knowledge. This "subtractive" approach requires a different mindset. It's about identifying and courageously removing the obstacles that are holding us back. By simplifying and focusing on what truly matters, we can unlock our potential and achieve a greater sense of clarity and purpose.`,
    '43-45': `(A) A young boy named Leo loved to draw. He spent hours creating vibrant worlds on paper, filled with fantastic creatures and towering castles. One day, his art teacher announced a national drawing competition. The grand prize was a scholarship to a prestigious art school. Leo was excited but also nervous. He saw the incredible drawings of his classmates and began to doubt his own abilities.
(B) He almost gave up, but his grandmother encouraged him. "Your art is special because it comes from your heart," she said. "Don't compare yourself to others. Just draw what you love." Taking her words to heart, Leo decided to create a piece that was uniquely his. He drew a magical forest inspired by the stories his grandmother used to tell him. It was filled with glowing mushrooms and friendly monsters, a world only he could imagine.
(C) Days turned into weeks as Leo worked on his drawing, pouring all his passion and imagination into it. He forgot about the competition and simply enjoyed the process of creating. When he finally finished, he felt a deep sense of satisfaction, regardless of the outcome. He submitted his work without any expectations.
(D) A few months later, a large envelope arrived. His hands trembled as he opened it. To his astonishment, he had won the grand prize. The judges praised his work for its originality and emotional depth. Leo realized his grandmother was right. The key to success wasn't being better than others, but being true to himself. His unique vision was his greatest strength.`
};
